parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(MAIN_DATABASE_URL): ''
    env(APPOINTMENT_DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:MAIN_DATABASE_URL)%'

            appointment:
                url: '%env(resolve:APPOINTMENT_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8
    orm:
#        auto_mapping: true

#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
#                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            appointment:
                connection: appointment
                mappings:
                    Appointment:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Appointment'
                        prefix: 'App\Entity\Appointment'
                        alias: Appointment